# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
      env:
        AWS_POSTGRES_ADDRESS: ${{secrets.AWS_POSTGRES_ADDRESS}}
        AWS_POSTGRES_DBNAME: ${{secrets.AWS_POSTGRES_DBNAME}}
        AWS_POSTGRES_PASSWORD: ${{secrets.AWS_POSTGRES_PASSWORD}}
        AWS_POSTGRES_PORT: ${{secrets.AWS_POSTGRES_PORT}}
        AWS_POSTGRES_USERNAME: ${{secrets.AWS_POSTGRES_USERNAME}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
        MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
        SALT_EMAIL: ${{secrets.SALT_EMAIL}}
        SECRET: ${{secrets.SECRET}}
